[plugins]
cargo-prebuilt = "https://github.com/sevenc-nanashi/mise-cargo-prebuilt"

[tools]
"github:sevenc-nanashi/aviutl2-cli" = { version = "0.7.1", bin = "au2.exe" }
"github:EmbarkStudios/cargo-about" = { version = "latest" }
"cargo-prebuilt:cargo-edit" = "latest"
"github:karoterra/aviutl2-aulua" = "latest"
